#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if xrandr -q | grep 'HDMI-1 connected'; then
  bspc monitor eDP-1 -d IV V VI
  bspc monitor HDMI-1 -d I II III
else 
  bspc monitor eDP-1 -d I II III
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

~/.screenlayout/display.sh
~/.config/polybar/launch.sh
bspc config focus_follows_pointer true
picom --experimental-backends &
bspc config border_width 1
xsetroot -cursor_name left_ptr &
synclient VertScrollDelta=-111
nitrogen --restore
light-locker &

#bspc config active_border_color     '#D373AB'
bspc config focused_border_color    '#5BB4D3'
bspc config normal_border_color     '#2E333C' #original
#bspc config normal_border_color     '#FFFFFF'
bspc config normal_border_color     '#1E222A'
bspc config presel_border_color     '#31aeff'
bspc config urgent_border_color     '#A40000'

bspc config active_locked_border_color      '#ff9e24'
bspc config focused_locked_border_color     '#ff9e24'
bspc config normal_locked_border_color      '#31aeff'

#bspc config window_gap 5 #tamaño de espacios

setxkbmap -layout latam
